FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["AppointmentScheduling.API/AppointmentScheduling.API.csproj", "AppointmentScheduling.API/"]
COPY ["HealthcareManagement.Shared/HealthcareManagement.Shared.csproj", "HealthcareManagement.Shared/"]
RUN dotnet restore "AppointmentScheduling.API/AppointmentScheduling.API.csproj"
COPY . .
WORKDIR "/src/AppointmentScheduling.API"
RUN dotnet build "AppointmentScheduling.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AppointmentScheduling.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AppointmentScheduling.API.dll"] 